import time

from conftest import *
from selenium.webdriver.common.by import By
import XPATH


class TestLogin:
    # Registration
    def test_registration(self, driver):
        WebDriverWait(driver, 10).until(EC.visibility_of_all_elements_located((By.XPATH, XPATH.cls_login_button)))
        cls_login_button = driver.find_element(By.XPATH, XPATH.cls_login_button)
        cls_login_button.click()
        WebDriverWait(driver, 10).until(EC.visibility_of_all_elements_located((By.XPATH, XPATH.cls_registration_button)))
        cls_registration_button = driver.find_element(By.XPATH, XPATH.cls_registration_button)
        cls_registration_button.click()
        WebDriverWait(driver, 10).until(EC.visibility_of_all_elements_located((By.XPATH, XPATH.cls_registration_name_button)))
        cls_registration_name_button = driver.find_element(By.XPATH, XPATH.cls_registration_name_button)
        cls_registration_name_button.send_keys('sob44ss4s4saka@ya.ru')
        WebDriverWait(driver, 10).until(EC.visibility_of_all_elements_located((By.XPATH, XPATH.user_password_or_registration_mail)))
        user_password_or_registration_mail = driver.find_element(By.XPATH, XPATH.user_password_or_registration_mail)
        user_password_or_registration_mail.send_keys('sob44ss4ss4aka@ya.ru')
        WebDriverWait(driver, 10).until(EC.visibility_of_all_elements_located((By.XPATH, XPATH.cls_registration_password_button)))
        cls_registration_password_button = driver.find_element(By.XPATH, XPATH.cls_registration_password_button)
        cls_registration_password_button.send_keys('123456')
        WebDriverWait(driver, 10).until(EC.visibility_of_all_elements_located((By.XPATH, XPATH.accept_button)))
        accept_button = driver.find_element(By.XPATH, XPATH.accept_button)
        accept_button.click()
        assert driver.current_url == 'https://stellarburgers.nomoreparties.site/login'

    def test_sign_in(self, driver):
        WebDriverWait(driver, 10).until(EC.visibility_of_all_elements_located((By.XPATH, XPATH.cls_login_button)))
        cls_login_button = driver.find_element(By.XPATH, XPATH.cls_login_button)
        cls_login_button.click()
        WebDriverWait(driver, 10).until(EC.visibility_of_all_elements_located((By.XPATH, XPATH.cls_registration_name_button)))
        cls_registration_name_button = driver.find_element(By.XPATH, XPATH.cls_registration_name_button)
        cls_registration_name_button.send_keys('sobaka@ya.ru')
        WebDriverWait(driver, 10).until(EC.visibility_of_all_elements_located((By.XPATH, XPATH.user_password_or_registration_mail)))
        user_password_or_registration_mail = driver.find_element(By.XPATH, XPATH.user_password_or_registration_mail)
        user_password_or_registration_mail.send_keys('123456')
        WebDriverWait(driver, 10).until(EC.visibility_of_all_elements_located((By.XPATH, XPATH.accept_button)))
        accept_button = driver.find_element(By.XPATH, XPATH.accept_button)
        accept_button.click()
        WebDriverWait(driver, 10).until(EC.visibility_of_all_elements_located((By.XPATH, XPATH.personal_area_button)))
        personal_area_button = driver.find_element(By.XPATH, XPATH.personal_area_button)
        personal_area_button.click()
        WebDriverWait(driver, 10).until(EC.visibility_of_all_elements_located((By.XPATH, XPATH.profile_button)))
        profile_button = driver.find_element(By.XPATH, XPATH.profile_button)
        return len(profile_button) > 0

    def test_error_password(self, driver):
        WebDriverWait(driver, 10).until(EC.visibility_of_all_elements_located((By.XPATH, XPATH.cls_login_button)))
        cls_login_button = driver.find_element(By.XPATH, XPATH.cls_login_button)
        cls_login_button.click()
        WebDriverWait(driver, 10).until(EC.visibility_of_all_elements_located((By.XPATH, XPATH.cls_registration_name_button)))
        cls_registration_name_button = driver.find_element(By.XPATH, XPATH.cls_registration_name_button)
        cls_registration_name_button.send_keys('sobaka@ya.ru')
        WebDriverWait(driver, 10).until(EC.visibility_of_all_elements_located((By.XPATH, XPATH.user_password_or_registration_mail)))
        user_password_or_registration_mail = driver.find_element(By.XPATH, XPATH.user_password_or_registration_mail)
        user_password_or_registration_mail.send_keys('12345')
        WebDriverWait(driver, 10).until(EC.visibility_of_all_elements_located((By.XPATH, XPATH.accept_button)))
        accept_button = driver.find_element(By.XPATH, XPATH.accept_button)
        accept_button.click()
        WebDriverWait(driver, 10).until(EC.visibility_of_all_elements_located((By.XPATH, XPATH.error_password_text)))
        error_password_text = driver.find_element(By.XPATH, XPATH.error_password_text)
        assert error_password_text.text == 'Некорректный пароль'

    def test_personal_area_log_in(self, driver):
        WebDriverWait(driver, 10).until(EC.visibility_of_all_elements_located((By.XPATH, XPATH.personal_area_button)))
        personal_area_button = driver.find_element(By.XPATH, XPATH.personal_area_button)
        personal_area_button.click()
        WebDriverWait(driver, 10).until(EC.visibility_of_all_elements_located((By.XPATH, XPATH.cls_registration_name_button)))
        cls_registration_name_button = driver.find_element(By.XPATH, XPATH.cls_registration_name_button)
        cls_registration_name_button.send_keys('sobaka@ya.ru')
        WebDriverWait(driver, 10).until(EC.visibility_of_all_elements_located((By.XPATH, XPATH.user_password_or_registration_mail)))
        user_password_or_registration_mail = driver.find_element(By.XPATH, XPATH.user_password_or_registration_mail)
        user_password_or_registration_mail.send_keys('123456')
        WebDriverWait(driver, 10).until(EC.visibility_of_all_elements_located((By.XPATH, XPATH.accept_button)))
        accept_button = driver.find_element(By.XPATH, XPATH.accept_button)
        accept_button.click()
        WebDriverWait(driver, 10).until(EC.visibility_of_all_elements_located((By.XPATH, XPATH.personal_area_button)))
        personal_area_button = driver.find_element(By.XPATH, XPATH.personal_area_button)
        personal_area_button.click()
        WebDriverWait(driver, 10).until(EC.visibility_of_all_elements_located((By.XPATH, XPATH.profile_button)))
        profile_button = driver.find_element(By.XPATH, XPATH.profile_button)
        return len(profile_button) > 0

    def test_sign_in_after_registration(self, driver):
        WebDriverWait(driver, 10).until(EC.visibility_of_all_elements_located((By.XPATH, XPATH.cls_login_button)))
        cls_login_button = driver.find_element(By.XPATH, XPATH.cls_login_button)
        cls_login_button.click()
        WebDriverWait(driver, 10).until(EC.visibility_of_all_elements_located((By.XPATH, XPATH.cls_registration_button)))
        cls_registration_button = driver.find_element(By.XPATH, XPATH.cls_registration_button)
        cls_registration_button.click()
        WebDriverWait(driver, 10).until(EC.visibility_of_all_elements_located((By.XPATH, XPATH.cls_button_for_regestr)))
        cls_button_for_regestr = driver.find_element(By.XPATH, XPATH.cls_button_for_regestr)
        cls_button_for_regestr.click()
        WebDriverWait(driver, 10).until(EC.visibility_of_all_elements_located((By.XPATH, XPATH.cls_registration_name_button)))
        cls_registration_name_button = driver.find_element(By.XPATH, XPATH.cls_registration_name_button)
        cls_registration_name_button.send_keys('sobaka@ya.ru')
        WebDriverWait(driver, 10).until(EC.visibility_of_all_elements_located((By.XPATH, XPATH.user_password_or_registration_mail)))
        user_password_or_registration_mail = driver.find_element(By.XPATH, XPATH.user_password_or_registration_mail)
        user_password_or_registration_mail.send_keys('123456')
        WebDriverWait(driver, 10).until(EC.visibility_of_all_elements_located((By.XPATH, XPATH.accept_button)))
        accept_button = driver.find_element(By.XPATH, XPATH.accept_button)
        accept_button.click()
        WebDriverWait(driver, 10).until(EC.visibility_of_all_elements_located((By.XPATH, XPATH.personal_area_button)))
        personal_area_button = driver.find_element(By.XPATH, XPATH.personal_area_button)
        personal_area_button.click()
        WebDriverWait(driver, 10).until(EC.visibility_of_all_elements_located((By.XPATH, XPATH.profile_button)))
        profile_button = driver.find_element(By.XPATH, XPATH.profile_button)
        return len(profile_button) > 0

    def test_sign_in_by_password_recovery_button(self, driver):
        WebDriverWait(driver, 10).until(EC.visibility_of_all_elements_located((By.XPATH, XPATH.cls_login_button)))
        cls_login_button = driver.find_element(By.XPATH, XPATH.cls_login_button)
        cls_login_button.click()
        WebDriverWait(driver, 10).until(EC.visibility_of_all_elements_located((By.XPATH, XPATH.password_recovery_button)))
        password_recovery_button = driver.find_element(By.XPATH, XPATH.password_recovery_button)
        password_recovery_button.click()
        WebDriverWait(driver, 10).until(EC.visibility_of_all_elements_located((By.XPATH, XPATH.cls_button_for_regestr)))
        cls_button_for_regestr = driver.find_element(By.XPATH, XPATH.cls_button_for_regestr)
        cls_button_for_regestr.click()
        WebDriverWait(driver, 10).until(EC.visibility_of_all_elements_located((By.XPATH, XPATH.cls_registration_name_button)))
        cls_registration_name_button = driver.find_element(By.XPATH, XPATH.cls_registration_name_button)
        cls_registration_name_button.send_keys('sobaka@ya.ru')
        WebDriverWait(driver, 10).until(EC.visibility_of_all_elements_located((By.XPATH, XPATH.user_password_or_registration_mail)))
        user_password_or_registration_mail = driver.find_element(By.XPATH, XPATH.user_password_or_registration_mail)
        user_password_or_registration_mail.send_keys('123456')
        WebDriverWait(driver, 10).until(EC.visibility_of_all_elements_located((By.XPATH, XPATH.accept_button)))
        accept_button = driver.find_element(By.XPATH, XPATH.accept_button)
        accept_button.click()
        WebDriverWait(driver, 10).until(EC.visibility_of_all_elements_located((By.XPATH, XPATH.personal_area_button)))
        personal_area_button = driver.find_element(By.XPATH, XPATH.personal_area_button)
        personal_area_button.click()
        WebDriverWait(driver, 10).until(EC.visibility_of_all_elements_located((By.XPATH, XPATH.profile_button)))
        profile_button = driver.find_element(By.XPATH, XPATH.profile_button)
        return len(profile_button) > 0

    def test_logout(self, driver, go_to_personal_account):
        WebDriverWait(driver, 10).until(EC.visibility_of_all_elements_located((By.XPATH, XPATH.cls_registration_name_button)))
        cls_registration_name_button = driver.find_element(By.XPATH, XPATH.cls_registration_name_button)
        cls_registration_name_button.send_keys('sobaka@ya.ru')
        WebDriverWait(driver, 10).until(EC.visibility_of_all_elements_located((By.XPATH, XPATH.user_password_or_registration_mail)))
        user_password_or_registration_mail = driver.find_element(By.XPATH, XPATH.user_password_or_registration_mail)
        user_password_or_registration_mail.send_keys('123456')
        WebDriverWait(driver, 10).until(EC.visibility_of_all_elements_located((By.XPATH, XPATH.accept_button)))
        accept_button = driver.find_element(By.XPATH, XPATH.accept_button)
        accept_button.click()
        WebDriverWait(driver, 10).until(EC.visibility_of_all_elements_located((By.XPATH, XPATH.personal_account)))
        personal_account = driver.find_element(By.XPATH, XPATH.personal_account)
        personal_account.click()
        WebDriverWait(driver, 10).until(EC.visibility_of_all_elements_located((By.XPATH, XPATH.logout_button)))
        logout_button = driver.find_element(By.XPATH, XPATH.logout_button)
        logout_button.click()
        WebDriverWait(driver, 10).until(EC.visibility_of_all_elements_located((By.XPATH, XPATH.accept_button)))
        accept_button = driver.find_element(By.XPATH, XPATH.accept_button)
        return len(accept_button) > 0
